services:
  - type: web
    name: webrtc-signaling-server
    env: node
    plan: free
    region: singapore
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
